# Generated by Django 4.2.4 on 2023-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("endereco", models.TextField(blank=True)),
                ("numero_casa", models.CharField(blank=True, max_length=10)),
                ("bairro", models.CharField(blank=True, max_length=50)),
                ("cidade", models.CharField(blank=True, max_length=50)),
                ("estado", models.CharField(blank=True, max_length=2)),
            ],
        ),
    ]
