# Generated by Django 4.2.4 on 2023-08-21 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0002_produto_capa_delete_livro"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Marcas",
            new_name="Marca",
        ),
    ]
