# Generated by Django 4.2.4 on 2023-08-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0002_rename_phone_number_cliente_numero_telefone_carrinho"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marcas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_marcas", models.CharField(max_length=100)),
                ("tipo_do_Produto", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="carrinho",
            name="total",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="bairro",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cidade",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="estado",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="numero_casa",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="numero_telefone",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idProduto", models.IntegerField()),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                ("validade", models.DateField(auto_now_add=True)),
                (
                    "marca",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ACosmeticos.marcas",
                    ),
                ),
            ],
        ),
    ]
