# Generated by Django 4.2.4 on 2023-08-27 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcarrinho",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ACosmeticos.produto",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="produto",
            name="marca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ACosmeticos.marca",
            ),
        ),
    ]
