# Generated by Django 4.2.4 on 2023-08-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0004_formapagamento_carrinho"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="tipo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
