# Generated by Django 4.2.4 on 2023-08-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0005_carrinho_total_da_compra_favorito"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormaPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_de_pagamento", models.CharField(max_length=100)),
                (
                    "quantidade_de_parcelas",
                    models.PositiveIntegerField(blank=True, default=1),
                ),
            ],
        ),
    ]
