# Generated by Django 4.2.4 on 2023-09-14 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0005_produto_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="tipo",
        ),
    ]
