# Generated by Django 4.2.4 on 2023-08-17 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0006_formapagamento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={"verbose_name_plural": "Clientes"},
        ),
    ]
