# Generated by Django 4.2.4 on 2023-08-18 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0007_alter_cliente_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cep",
            field=models.CharField(default=0, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(default=0, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ACosmeticos.marcas"
            ),
        ),
    ]
