# Generated by Django 4.2.4 on 2023-10-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0008_rename_total_da_compra_carrinho_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marca",
            name="sub_produto",
            field=models.CharField(default="valor_padrao_aqui", max_length=100),
        ),
    ]
