# Generated by Django 4.2.4 on 2023-08-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0008_cliente_cep_cliente_cpf_alter_produto_marca"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="quantia",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cep",
            field=models.CharField(default="0", max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(default="0", max_length=11, null=True),
        ),
    ]
