# Generated by Django 4.2.4 on 2023-08-18 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0010_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcarrinho",
            name="compra",
            field=models.ForeignKey(
                default= 1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="ACosmeticos.compra",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Carrinho"),
                    (2, "Realizado"),
                    (3, "Pago"),
                    (4, "Entregue"),
                ],
                default=1,
                null=True,
            ),
        ),
    ]
