# Generated by Django 4.2.4 on 2023-10-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0011_remove_marca_sub_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemcarrinho",
            name="compra",
        ),
        migrations.CreateModel(
            name="CompraItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ACosmeticos.compra",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ACosmeticos.produto",
                    ),
                ),
            ],
        ),
    ]
