# Generated by Django 4.2.4 on 2023-08-18 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0012_alter_itemcarrinho_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcarrinho",
            name="compra",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="ACosmeticos.compra",
            ),
        ),
    ]
