# Generated by Django 4.2.4 on 2023-10-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0012_remove_itemcarrinho_compra_compraitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrinho",
            name="total",
        ),
        migrations.AddField(
            model_name="carrinho",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Carrinho"),
                    (2, "Realizado"),
                    (3, "Pago"),
                    (4, "Entregue"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="itemcarrinho",
            name="carrinho",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="ACosmeticos.carrinho",
            ),
        ),
    ]
