# Generated by Django 4.2.4 on 2023-10-16 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ACosmeticos", "0013_remove_carrinho_total_carrinho_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compraitem",
            name="compra",
        ),
        migrations.RemoveField(
            model_name="compraitem",
            name="produto",
        ),
        migrations.DeleteModel(
            name="Compra",
        ),
        migrations.DeleteModel(
            name="CompraItem",
        ),
    ]
